### PR TITLE
feature(react): update react and react dom to 16.5

### PR DESCRIPTION
**Pull request by vinicius33**
In order to use the new `React-Profiler` we've got to update `React and React-DOM` to `16.5`.

### CODE REVIEW

**Comment by vinicius33** [comment]
@emeraquino totally agree with you and I intend to do so later. However, as it's a brand new version I'm a bit skeptical for a few days or so until everybody says it works fine. 🤣

**Comment by emeraquino** [comment]
@vinicius33 But it's a minor update right? Which means it contains probably fixes from `16.5.0` :)

**Comment by vinicius33** [comment]
@emeraquino True that! Done. Thanks a lot.

**Pull request merged**
